#!/usr/bin/env python3
"""Convert a llama2.c float32 checkpoint (+ its tokenizer) into the INT8 blob
the accelerator-backed inference code (llm_core.h) consumes.

Every weight matrix W[rows][K] becomes int8 with a per-ROW symmetric scale
(scale = max|w| / 127), padded so rows and K are multiples of 8 (the tile
edge of the accelerator). Padding is zero, so it never changes a result.
Norm weights, RoPE tables and the tokenizer stay float/bytes.

Blob layout: 16 uint32 header words, then a table of section offsets, then
the 8-byte-aligned sections. See SECTIONS below for the fixed order.
"""
import struct, sys
import numpy as np

def pad8(n): return (n + 7) // 8 * 8

def read_model(path):
    d = open(path, 'rb').read()
    dim, hid, nl, nh, nkv, vocab, seq = struct.unpack('7i', d[:28])
    shared = vocab > 0
    vocab = abs(vocab)
    f = np.frombuffer(d[28:], dtype=np.float32)
    hs = dim // nh; kvd = nkv * hs
    pos = 0
    def take(n, shape):
        nonlocal pos
        a = f[pos:pos + n].reshape(shape); pos += n; return a
    w = {}
    w['embed'] = take(vocab * dim, (vocab, dim))
    w['rms_att'] = take(nl * dim, (nl, dim))
    w['wq'] = take(nl * dim * dim, (nl, dim, dim))
    w['wk'] = take(nl * kvd * dim, (nl, kvd, dim))
    w['wv'] = take(nl * kvd * dim, (nl, kvd, dim))
    w['wo'] = take(nl * dim * dim, (nl, dim, dim))
    w['rms_ffn'] = take(nl * dim, (nl, dim))
    w['w1'] = take(nl * hid * dim, (nl, hid, dim))
    w['w2'] = take(nl * dim * hid, (nl, dim, hid))
    w['w3'] = take(nl * hid * dim, (nl, hid, dim))
    w['rms_final'] = take(dim, (dim,))
    w['rope_cos'] = take(seq * hs // 2, (seq, hs // 2))
    w['rope_sin'] = take(seq * hs // 2, (seq, hs // 2))
    assert shared and pos == len(f), (shared, pos, len(f))
    cfg = dict(dim=dim, hidden=hid, layers=nl, heads=nh, kv_heads=nkv, vocab=vocab, seq=seq)
    return cfg, w

def quant_rows(m, rows_pad, k_pad):
    """m: [rows][K] float -> (int8 [rows_pad][k_pad], float32 scales [rows_pad])"""
    rows, k = m.shape
    q = np.zeros((rows_pad, k_pad), dtype=np.int8)
    s = np.ones(rows_pad, dtype=np.float32)
    for r in range(rows):
        mx = float(np.abs(m[r]).max())
        sc = mx / 127.0 if mx > 0 else 1.0
        q[r, :k] = np.clip(np.rint(m[r] / sc), -127, 127).astype(np.int8)
        s[r] = sc
    return q, s

def read_tokenizer(path):
    d = open(path, 'rb').read()
    maxlen, = struct.unpack('i', d[:4]); p = 4; toks = []; scores = []
    while p < len(d):
        sc, ln = struct.unpack('fi', d[p:p + 8]); p += 8
        toks.append(d[p:p + ln]); scores.append(sc); p += ln
    return toks, scores

def main(model, tok, out):
    cfg, w = read_model(model)
    toks, tok_scores = read_tokenizer(tok)
    assert len(toks) == cfg['vocab'], (len(toks), cfg['vocab'])
    dim, hid, nl = cfg['dim'], cfg['hidden'], cfg['layers']
    hid_p = pad8(hid); kvd = cfg['kv_heads'] * (dim // cfg['heads'])
    assert dim % 8 == 0 and kvd % 8 == 0

    sections = []  # (name, bytes)
    def add(name, arr): sections.append((name, np.ascontiguousarray(arr).tobytes()))
    add('rms_att', w['rms_att'].astype(np.float32)); add('rms_ffn', w['rms_ffn'].astype(np.float32))
    add('rms_final', w['rms_final'].astype(np.float32))
    add('rope_cos', w['rope_cos'].astype(np.float32)); add('rope_sin', w['rope_sin'].astype(np.float32))
    offs = [0]; blob = b''
    for t in toks: blob += t; offs.append(len(blob))
    add('tok_off', np.array(offs, dtype=np.uint32)); sections.append(('tok_data', blob))
    q, s = quant_rows(w['embed'], cfg['vocab'], dim); add('embed_q', q); add('embed_s', s)
    for name, rows, rows_p, k, k_p in [
            ('wq', dim, dim, dim, dim), ('wk', kvd, kvd, dim, dim), ('wv', kvd, kvd, dim, dim),
            ('wo', dim, dim, dim, dim), ('w1', hid, hid_p, dim, dim), ('w3', hid, hid_p, dim, dim),
            ('w2', dim, dim, hid, hid_p)]:
        qs, ss = zip(*[quant_rows(w[name][l], rows_p, k_p) for l in range(nl)])
        add(name + '_q', np.stack(qs)); add(name + '_s', np.stack(ss))
    # appended LAST so every earlier section index is unchanged (BPE merge scores for on-chip tokenizing)
    add('tok_scores', np.array(tok_scores, dtype=np.float32))

    header_words = 16
    table_words = 2 * len(sections)  # (offset, size) per section
    base = (header_words + table_words) * 4
    def al(x): return (x + 7) // 8 * 8
    pos = al(base); table = []; body = b''
    for name, b in sections:
        table.append((pos, len(b))); body += b + b'\0' * (al(len(b)) - len(b)); pos += al(len(b))
    hdr = [0x384c4c4d, cfg['dim'], cfg['hidden'], hid_p, cfg['layers'], cfg['heads'],
           cfg['kv_heads'], cfg['vocab'], cfg['seq'], len(sections)] + [0] * 6
    out_b = struct.pack('16I', *hdr)
    for o, n in table: out_b += struct.pack('2I', o, n)
    out_b += b'\0' * (al(base) - len(out_b)) + body
    open(out, 'wb').write(out_b)
    with open(out.replace('.bin', '_sections.h'), 'w') as h:
        h.write('// generated by quantize.py -- index of each section in the blob table\n')
        for i, (name, _) in enumerate(sections): h.write('#define SEC_%s %d\n' % (name.upper(), i))
    print('wrote', out, len(out_b), 'bytes,', len(sections), 'sections; cfg', cfg, 'hidden_pad', hid_p)

if __name__ == '__main__':
    main(*sys.argv[1:4])
