CC ?= riscv64-unknown-linux-gnu-gcc
CFLAGS = -O2 -static
LDFLAGS = -static

videoplayer-netstream: videoplayer_netstream.c
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)

native: videoplayer_netstream.c
	gcc -O2 $< -o videoplayer-netstream-native

clean:
	rm -f videoplayer-netstream videoplayer-netstream-native
