#!/usr/bin/env python3
"""SmolLM2-135M-Instruct (HF safetensors) -> INT8 blob in the same layout llm_core.h reads (see ../llm/quantize.py).
Per-row symmetric INT8 weights (scale = max|w|/127). Q/K rows are permuted per head so the C code's
interleaved-pair RoPE equals HF's rotate_half: new row 2j <- old row j, new row 2j+1 <- old row j+HS/2."""
import sys, struct, numpy as np
sys.path.insert(0, '../llm')
from quantize import quant_rows, pad8
import ref_smol as R
MAXPOS = 256
def perm_heads(w, heads):     # w: [heads*HS][in]
    hs = R.HS; out = np.empty_like(w)
    for h in range(heads):
        blk = w[h * hs:(h + 1) * hs]; o = np.empty_like(blk); o[0::2] = blk[:hs // 2]; o[1::2] = blk[hs // 2:]; out[h * hs:(h + 1) * hs] = o
    return out
def main(outp):
    W = R.load(); L = R.L; D = R.D; H = R.H; KV = R.KV; FF = R.FF; V = R.V; HS = R.HS
    secs = []
    def add(name, arr): secs.append((name, np.ascontiguousarray(arr).tobytes()))
    lw = lambda fmt: np.stack([W[f'model.layers.{l}.{fmt}'] for l in range(L)]).astype(np.float32)
    add('rms_att', lw('input_layernorm.weight')); add('rms_ffn', lw('post_attention_layernorm.weight')); add('rms_final', W['model.norm.weight'])
    cos, sin = R.rope_tables(MAXPOS); add('rope_cos', cos); add('rope_sin', sin)     # [MAXPOS][HS/2]
    add('tok_off', np.zeros(2, np.uint32)); secs.append(('tok_data', b'\0' * 8))    # tokenizer lives on the PC side
    q, s = quant_rows(W['model.embed_tokens.weight'], V, D); add('embed_q', q); add('embed_s', s)
    mats = [('wq', 'self_attn.q_proj.weight', D, D, H), ('wk', 'self_attn.k_proj.weight', KV * HS, D, KV), ('wv', 'self_attn.v_proj.weight', KV * HS, D, 0),
            ('wo', 'self_attn.o_proj.weight', D, D, 0), ('w1', 'mlp.gate_proj.weight', FF, D, 0), ('w3', 'mlp.up_proj.weight', FF, D, 0), ('w2', 'mlp.down_proj.weight', D, FF, 0)]
    for name, key, rows, k, ph in mats:
        qs, ss = [], []
        for l in range(L):
            w = W[f'model.layers.{l}.{key}']
            if ph: w = perm_heads(w, ph)
            qq, sc = quant_rows(w, rows, k); qs.append(qq); ss.append(sc)
        add(name + '_q', np.stack(qs)); add(name + '_s', np.stack(ss)); print('quantized', name, flush=True)
    add('tok_scores', np.zeros(2, np.float32))
    base = (16 + 2 * len(secs)) * 4; al = lambda x: (x + 7) // 8 * 8
    pos = al(base); table = []; body = b''
    for n, b in secs: table.append((pos, len(b))); body += b + b'\0' * (al(len(b)) - len(b)); pos += al(len(b))
    hdr = [0x384c4c4d, D, FF, FF, L, H, KV, V, MAXPOS, len(secs)] + [0] * 6
    ob = struct.pack('16I', *hdr) + b''.join(struct.pack('2I', o, n) for o, n in table)
    ob += b'\0' * (al(base) - len(ob)) + body; open(outp, 'wb').write(ob)
    open(outp.replace('.bin', '_sections.h'), 'w').write('// generated by convert_smol.py\n' + ''.join('#define SEC_%s %d\n' % (n.upper(), i) for i, (n, _) in enumerate(secs)))
    print('wrote', outp, len(ob), 'bytes;', len(secs), 'sections')
if __name__ == '__main__': main(sys.argv[1] if len(sys.argv) > 1 else 'smol135_i8.bin')
