// Generated by CIRCT firtool-1.75.0
module PMAChecker(	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:18:7]
  input  [31:0] io_paddr,	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  output        io_resp_r,	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  output        io_resp_w,	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  output        io_resp_pp,	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  output        io_resp_al,	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  output        io_resp_aa,	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  output        io_resp_x,	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  output        io_resp_eff	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
);

  wire [8:0] _GEN = io_paddr[20:12] ^ 9'h100;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:31]
  wire [9:0] _GEN_0 = io_paddr[25:16] ^ 10'h200;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:31]
  wire       legal_address = io_paddr[31:12] == 20'h0 | {io_paddr[31:13], ~(io_paddr[12])} == 20'h0 | {io_paddr[31:14], ~(io_paddr[13:12])} == 20'h0 | {io_paddr[31:17], ~(io_paddr[16])} == 16'h0 | {io_paddr[31:21], _GEN} == 20'h0 | {io_paddr[31:21], io_paddr[20:12] ^ 9'h110} == 20'h0 | {io_paddr[31:26], _GEN_0} == 16'h0 | {io_paddr[31:28], ~(io_paddr[27:26])} == 6'h0 | {io_paddr[31:29], io_paddr[28:12] ^ 17'h10020} == 20'h0 | io_paddr[31:14] == 18'h20000;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{31,41,46,59}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14, :36:58]
  wire [2:0] _GEN_1 = {io_paddr[27], io_paddr[20], io_paddr[16]};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{31,41,46}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  wire [2:0] _GEN_2 = {io_paddr[27], _GEN[8], io_paddr[12]};	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{31,41,46}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:19:14]
  assign io_resp_r = legal_address;	// @[generators/rocket-chip/src/main/scala/rocket/PMA.scala:18:7, :36:58]
  assign io_resp_w = legal_address & (~(|_GEN_1) | ~(|_GEN_2) | io_paddr[27]);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{41,46,59}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:18:7, :19:14, :36:58, :39:19, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:629:89]
  assign io_resp_pp = legal_address & (~(|_GEN_1) | ~(|_GEN_2) | io_paddr[27]);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{41,46,59}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:18:7, :19:14, :36:58, :39:19, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:629:89]
  assign io_resp_al = legal_address & (~(|_GEN_1) | ~(|_GEN_2) | io_paddr[27]);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{41,46,59}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:18:7, :19:14, :36:58, :39:19, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:629:89]
  assign io_resp_aa = legal_address & (~(|_GEN_1) | ~(|_GEN_2) | io_paddr[27]);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{41,46,59}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:18:7, :19:14, :36:58, :39:19, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:629:89]
  assign io_resp_x = legal_address & ({io_paddr[31], io_paddr[28:27], io_paddr[25], io_paddr[20], io_paddr[16], io_paddr[13:12]} == 8'h0 | {io_paddr[31], io_paddr[28:27], io_paddr[25], io_paddr[20], io_paddr[16], ~(io_paddr[13:12])} == 8'h0 | {io_paddr[31], io_paddr[28:27], io_paddr[25], io_paddr[20], ~(io_paddr[16])} == 6'h0 | {~(io_paddr[31]), io_paddr[28:27], io_paddr[25], io_paddr[20], io_paddr[16]} == 6'h0);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{31,41,46,59}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:18:7, :19:14, :36:58, :39:19, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:629:89]
  assign io_resp_eff = legal_address & ({io_paddr[31], io_paddr[27], io_paddr[25], io_paddr[20], io_paddr[16], io_paddr[13]} == 6'h0 | {io_paddr[31], io_paddr[27], io_paddr[25], _GEN[8], io_paddr[13:12]} == 6'h0 | {io_paddr[31], io_paddr[27], _GEN_0[9], io_paddr[20], io_paddr[16]} == 5'h0 | {io_paddr[31], ~(io_paddr[27])} == 2'h0);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:139:{31,41,46,59}, generators/rocket-chip/src/main/scala/rocket/PMA.scala:18:7, :19:14, :36:58, :39:19, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:629:89]
endmodule

