#!/usr/bin/env python3
"""
Assemble multiple compiled firmware.mem files into ONE flat DMI transaction
ROM for DmiAutoloader.v, with a per-program (base, length) index, and splice
the result directly into DmiAutoloader.v between its
"BEGIN/END GENERATED ROM SECTION" marker comments.

This never hand-types hex: every word comes straight from objcopy's Verilog
output, parsed and re-emitted as Verilog literals. Run from ninad/basys3/:

    python3 gen_dmi_rom_multi.py
"""
import os

DMCONTROL   = 0x10
SBCS        = 0x38
SBADDRESS0  = 0x39
SBDATA0     = 0x3c

DTIM_BASE   = 0x80000000
CLINT_MSIP0 = 0x02000000

# (index, name, path to firmware.mem, relative to ninad/)
PROGRAMS = [
    (0, "hello",      "firmware.mem"),
    (1, "mandelbrot", "mandelbrot/firmware.mem"),
    (2, "calculator", "calculator/firmware.mem"),
    (3, "fibonacci",  "fibonacci/firmware.mem"),
    (4, "primes",     "primes/firmware.mem"),
    (5, "bubblesort", "bubblesort/firmware.mem"),
    (6, "gameoflife", "gameoflife/firmware.mem"),
    (7, "timestable", "timestable/firmware.mem"),
    (8, "spiral",     "spiral/firmware.mem"),
]

NINAD_DIR = os.path.join(os.path.dirname(__file__), "..")
AUTOLOADER_PATH = os.path.join(os.path.dirname(__file__), "DmiAutoloader.v")

BEGIN_MARKER = "  // BEGIN GENERATED ROM SECTION"
END_MARKER = "  // END GENERATED ROM SECTION"


def parse_mem(path):
    mem = {}
    addr = None
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith('@'):
                addr = int(line[1:], 16)
                continue
            for tok in line.split():
                mem[addr] = int(tok, 16)
                addr += 1
    return mem


def words_from_mem(mem):
    lo, hi = min(mem), max(mem)
    assert lo == DTIM_BASE, f"expected base 0x80000000, got 0x{lo:x}"
    n = hi - lo + 1
    n_padded = (n + 3) // 4 * 4
    words = []
    for i in range(0, n_padded, 4):
        b = [mem.get(lo + i + k, 0) for k in range(4)]
        words.append(b[0] | (b[1] << 8) | (b[2] << 16) | (b[3] << 24))
    return words


def xact_for_program(words):
    xact = []
    xact.append((DMCONTROL, 0x00000001))
    xact.append((DMCONTROL, 0x00000003))
    xact.append((SBCS, 0x00050000))
    xact.append((SBADDRESS0, DTIM_BASE))
    for w in words:
        xact.append((SBDATA0, w))
    xact.append((SBADDRESS0, CLINT_MSIP0))
    xact.append((SBDATA0, 0x00000001))
    xact.append((DMCONTROL, 0x00000001))
    return xact


def main():
    all_xact = []
    prog_base = []
    prog_len = []
    prog_names = []

    for idx, name, relpath in PROGRAMS:
        mem_path = os.path.join(NINAD_DIR, relpath)
        mem = parse_mem(mem_path)
        words = words_from_mem(mem)
        xact = xact_for_program(words)
        prog_base.append(len(all_xact))
        prog_len.append(len(xact))
        prog_names.append(name)
        all_xact.extend(xact)
        print(f"  program {idx} ({name}): {len(words)} data words, {len(xact)} transactions, base={prog_base[-1]}")

    total = len(all_xact)
    num_progs = len(PROGRAMS)

    lines = []
    lines.append("  // BEGIN GENERATED ROM SECTION -- do not hand-edit this block.")
    lines.append("  // Regenerated by splicing (Python, string replace between the BEGIN/END")
    lines.append("  // marker comments themselves -- not by retyping hex) with:")
    lines.append("  //   python3 gen_dmi_rom_multi.py")
    lines.append("  // Program index: " + ", ".join(f"{i}={n}" for i, n, _ in PROGRAMS))
    lines.append(f"  localparam NUM_PROGS = {num_progs};")
    lines.append(f"  localparam TOTAL_XACT = {total};")
    lines.append("  reg [6:0]  ALL_ADDR [0:TOTAL_XACT-1];")
    lines.append("  reg [31:0] ALL_DATA [0:TOTAL_XACT-1];")
    lines.append("  reg [10:0] PROG_BASE [0:NUM_PROGS-1];")
    lines.append("  reg [10:0] PROG_LEN  [0:NUM_PROGS-1];")
    lines.append("  initial begin")
    for i, (a, d) in enumerate(all_xact):
        lines.append(f"    ALL_ADDR[{i}] = 7'h{a:02x}; ALL_DATA[{i}] = 32'h{d:08x};")
    for i in range(num_progs):
        lines.append(f"    PROG_BASE[{i}] = 11'd{prog_base[i]}; PROG_LEN[{i}] = 11'd{prog_len[i]}; // {prog_names[i]}")
    lines.append("  end")
    lines.append("  // END GENERATED ROM SECTION")

    with open(AUTOLOADER_PATH) as f:
        content = f.read()

    begin_i = content.index(BEGIN_MARKER)
    end_i = content.index(END_MARKER) + len(END_MARKER)
    new_content = content[:begin_i] + "\n".join(lines) + content[end_i:]

    with open(AUTOLOADER_PATH, "w") as f:
        f.write(new_content)

    print(f"\nSpliced {total} total transactions across {num_progs} programs into {AUTOLOADER_PATH}")


if __name__ == "__main__":
    main()
