#!/usr/bin/env python3
"""
Generate the DMI transaction table (addr,data pairs) for DmiAutoloader.v
from a compiled firmware.mem (riscv64-unknown-elf-objcopy -O verilog output).

This exists so program transaction tables are generated mechanically, not
hand-transcribed -- avoiding the exact class of transcription risk that was
manually cross-checked (via objdump diff) for the original Hello Worldí
table. Usage:

    python3 gen_dmi_rom.py <firmware.mem> <verilog_array_name>

Prints Verilog initializer lines for the fixed setup/data/wake/release
sequence used by DmiAutoloader.v -- paste directly into the ROM tables.
"""
import sys

DMCONTROL   = 0x10
SBCS        = 0x38
SBADDRESS0  = 0x39
SBDATA0     = 0x3c

DTIM_BASE   = 0x80000000
CLINT_MSIP0 = 0x02000000


def parse_mem(path):
    mem = {}
    addr = None
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith('@'):
                addr = int(line[1:], 16)
                continue
            for tok in line.split():
                mem[addr] = int(tok, 16)
                addr += 1
    return mem


def words_from_mem(mem):
    lo, hi = min(mem), max(mem)
    assert lo == DTIM_BASE, f"expected base 0x80000000, got 0x{lo:x}"
    n = hi - lo + 1
    n_padded = (n + 3) // 4 * 4
    words = []
    for i in range(0, n_padded, 4):
        b = [mem.get(lo + i + k, 0) for k in range(4)]
        words.append(b[0] | (b[1] << 8) | (b[2] << 16) | (b[3] << 24))
    return words


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    mem_path, array_prefix = sys.argv[1], sys.argv[2]
    mem = parse_mem(mem_path)
    words = words_from_mem(mem)

    xact = []
    xact.append((DMCONTROL, 0x00000001))            # dmactive=1
    xact.append((DMCONTROL, 0x00000003))            # dmactive=1, ndmreset=1
    xact.append((SBCS, 0x00050000))                 # sbaccess=32bit, sbautoincrement=1
    xact.append((SBADDRESS0, DTIM_BASE))
    for w in words:
        xact.append((SBDATA0, w))
    xact.append((SBADDRESS0, CLINT_MSIP0))
    xact.append((SBDATA0, 0x00000001))               # arm IPI (while still in reset)
    xact.append((DMCONTROL, 0x00000001))             # ndmreset=0 -- release reset last

    n = len(xact)
    print(f"// Generated by gen_dmi_rom.py from {mem_path} -- {len(words)} data words, {n} total transactions")
    print(f"localparam {array_prefix.upper()}_NUM_XACT = {n};")
    for i, (a, d) in enumerate(xact):
        print(f"{array_prefix}_ADDR[{i}] = 7'h{a:02x}; {array_prefix}_DATA[{i}] = 32'h{d:08x};")


if __name__ == "__main__":
    main()
